language: node_js
node_js: node

script:
  - npm test
  - npm run build:debug
  - npm run build:prod
  - npm run doc:build

deploy:
  provider: npm
  email: folkvir@outlook.fr
  api_key: $NPM
  on:
    tags: true
    repo: RAN3D/n2n-wrtc
notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
